### PR TITLE
Add periodic CodeQL scan

### PR DESCRIPTION
**Pull request by JAORMX**
This will throw periodic alerts on the code base which will notify us if we have security issues. It also will run code scanning on each pull request.

### CODE REVIEW

**Review by joelrebel — APPROVED** [review]
🚀

**Comment by joelrebel** [comment]
@Mergifyio refresh

**Comment by joelrebel** [comment]
@Mergifyio refresh

**Comment by JAORMX** [comment]
https://github.com/Mergifyio refresh

**Pull request merged**
